trigger:
- master

pool:
  name: default
  
steps:
- task: Maven@1
  inputs:
    mavenPomFile: 'time-tracker/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'mvn package'
