trigger:
- master

pool:
  name: ubuntu20.04.6
  
steps:
- task: Maven@1
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'mvn package'
